name: tidy_cam
description: "Tidy Cam - Tidy Tool for Camera for Photographing Tools"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1
  camera: ^0.11.1
  permission_handler: ^12.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  gallery_saver_plus: ^3.2.8
  shopify_flutter: ^2.6.0
  flutter_bloc: ^8.1.3
  graphql_flutter: ^5.1.2
  flutter_dotenv: ^5.1.0
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env