name: tidy_cam
description: "Tidy Cam - Tidy Tool for Camera for Photographing Tools"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1
  camera: ^0.11.1
  permission_handler: ^12.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  gallery_saver_plus: ^3.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
